---
services:

  lindwen_fr:
    container_name: lindwen_fr
    image: ghcr.io/static-web-server/static-web-server:2
    restart: unless-stopped
    environment:
      - SERVER_ROOT=/var/public
    volumes:
      - ./public:/var/public:ro
    labels:
      #-- WatchTower --#
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
...
